package eu.trentorise.game.challenges.model;

public enum ChallengeType {
	PERCENT, BSPERCENT, TRIPNUMBER, BSTRIPNUMBER, BADGECOLLECTION, RECOMMENDATION, 
		POINTSEARNED, LEADERBOARDPOSITION, ZEROIMPACT, NEXTBADGE, NOOP 
}